api_platform:
  title: Hello API Platform
  version: 1.0.0
  # Good defaults for REST APIs
  defaults:
    stateless: false
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
  
  eager_loading:
    max_joins: 200

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header


