nelmio_cors:
  defaults:
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Access-Control-Allow-Origin"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      expose_headers: ["Access-Control-Allow-Origin"]
      allow_credentials: true
      max_age: 3600
