name: Create .env for deployment

on:
  push:
    branches: ["deployment"]
  pull_request:
    branches: ["deployment"]

jobs:
  create-env:
    name: Create env file
    runs-on: ubuntu-latest
    steps:
      - name: Generate env file
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
